name: "🐛 Bug report"
description: Report errors or unexpected behavior in coteafs-appium framework.
title: "[Bug]"
labels:
  - "type: bug"
body:
  - type: input
    attributes:
      label: Version?
      placeholder: 4.0.0
      description: The version of coteafs-appium which caused the issue.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Platform?
      description: Which platform caused the issue?
      multiple: false
      options:
        - Android
        - iOS
        - Both
        - NA
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: We highly suggest including a screenshots and a bug report log (GitHub Gist link).
      placeholder: Tell us the steps required to trigger your bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✔️ Expected Behavior
      placeholder: What were you expecting?
    validations:
      required: true

  - type: textarea
    attributes:
      label: ❌ Actual Behavior
      placeholder: What happened instead?
    validations:
      required: true
